# NUMPY LIBRARY

# import numpy as np

In [1]:
import numpy as np

# Checking NumPy Version

In [2]:
version=np.__version__
print(version)

1.23.5


# 1. NumPy Creating Arrays

In [3]:
#NumPy is used to work with arrays. The array object in NumPy is called ndarray.
#We can create a NumPy ndarray object by using the array() function.

#Dimensions in Arrays :A dimension in arrays is one level of array depth (nested arrays).

nested array:  are arrays that have arrays as their elements.

# 0-D Arrays

In [4]:
arr=np.array(42)
print(arr)

42


# 1-D Arrays

In [5]:
arr=np.array([1,2,3])
print(arr)

[1 2 3]


# 2-D Arrays

In [6]:
arr=np.array([[1,2,3],[5,6,7]])
print(arr)

[[1 2 3]
 [5 6 7]]


# 3-D Arrays

In [7]:
arr=np.array([[[1,2,3],[4,6,7]],[[1,11,12],[13,14,15]]])
print(arr)

[[[ 1  2  3]
  [ 4  6  7]]

 [[ 1 11 12]
  [13 14 15]]]


# 2.Check Number of Dimensions?ndim

In [8]:
a=np.array(42)
b=np.array([1,2,3])
c=np.array([[1,2,3],[5,6,7]])
d=np.array([[[1,2,3],[4,6,7]],[[1,11,12],[13,14,15]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


# 3.Higher Dimensional Arrays,ndmin


In [9]:
b=np.array([1,2,3],ndmin=5)
print(b)
           

[[[[[1 2 3]]]]]


In [10]:
print(b.ndim)

5


# 4.Array indexing(acces array elements)

# 1d array

In [11]:
import numpy as np
arr=np.array([1,2,3])
print(arr[0])# to get first elemnt in 1d array

1


In [12]:
print(arr[1])# to get second elemnt in 1d array

2


In [13]:
print(arr[-1])# to get last elemnt in 1d array

3


In [14]:
print(arr[1]+arr[2])

5


In [15]:
#0-first,1-second,....-1 last,-2 second last

# 2d array

In [16]:
arr2=np.array([[1,2,3],[4,5,6]])
print(arr2)#2*3 matrix

[[1 2 3]
 [4 5 6]]


In [17]:
print(arr2[0])# first element

[1 2 3]


In [18]:
print(arr2[1])# second  element

[4 5 6]


In [19]:
print('second element on first row',arr2[0,1])#0-row,1-column

second element on first row 2


In [20]:
arr2=np.array([[1,2,3,5,6],[6,2,4,5,6]])
print('third element on second row',arr2[1,2])

third element on second row 4


In [21]:
arr2=np.array([[1,2,3],[4,5,6]])
print(arr2[0,0])# 11 nu pakaram 00 first row first column

1


In [22]:
arr2=np.array([[1,2,3],[4,5,6]])
print(arr2[1,-1])# second row last column

6


# 3d array

In [23]:
arr3=np.array([[[1,2,3],[4,5,6]], [[6,2,3],[4,5,6]]])
print(arr3)

[[[1 2 3]
  [4 5 6]]

 [[6 2 3]
  [4 5 6]]]


In [24]:
print(arr3[0,1,2])#Access the third element of the second array of the first array:

6


# 5. slicing array

# 1d array

In [25]:
arr1=np.array([1,2,3,4,5,6,7,8,9,10])
print(arr1)

[ 1  2  3  4  5  6  7  8  9 10]


In [26]:
print(arr1[1:3])# 1 included 3 excludes

[2 3]


In [27]:
print(arr1[:3])

[1 2 3]


In [28]:
print(arr1[1:])

[ 2  3  4  5  6  7  8  9 10]


In [29]:
print(arr1[-3:-1])# -1 excluded

[8 9]


In [30]:
print(arr1[1:3:2])# 2 is the step size ,if there is no step by default is 1

[2]


In [31]:
print(arr1[1:8:2])# step 2 means difference 2

[2 4 6 8]


# 2d array

In [32]:
arr2=np.array([[1,2,3],[4,5,6],[3,4,5],[9,1,6]])
print(arr2)

[[1 2 3]
 [4 5 6]
 [3 4 5]
 [9 1 6]]


In [33]:
print(arr2[1,0:2])# 1 means 2nd row(second element), 0:2 means [first,second]

[4 5]


In [34]:
# From the second element, slice elements from index 1 to index 4 (not included)

In [35]:
print(arr2[0:2,1]) # second column 0,1 elents

[2 5]


In [36]:
print(arr2[1:3,2])# third column 1,2 elements

[6 5]


In [37]:
print(arr2[1:3,0:2]) # row 2 ,3  and column 1,2

[[4 5]
 [3 4]]


In [38]:
print(arr2[2:,1:])

[[4 5]
 [1 6]]


# 6. datatypes in numpy

In [39]:
# i - integer
# b - boolean
# u - unsigned integer
# f - float
# c - complex float
# m - timedelta
# M - datetime
# O - object
# S - string
# U - unicode string
# V - fixed chunk of memory for other type ( void )

# Checking the Data Type of an Array- dtype

In [40]:
arr=np.array([1,2,3,4,5,6,7,8,9,10])
print(arr.dtype)

int32


In [41]:
arr=np.array(['banana','mango','apple'])
print(arr.dtype)

<U6


# Creating Arrays With a Defined Data Type(chnging datatype)

In [42]:
arr=np.array([1,2,3,4,5,6,7,8,9,10],dtype='S')
print(arr.dtype)

|S2


In [43]:
print(arr)

[b'1' b'2' b'3' b'4' b'5' b'6' b'7' b'8' b'9' b'10']


In [44]:
arr=np.array([1,2,3,4,5,6,7,8,9,10],dtype='i4')# i is integer 4 is size 4 bytes
print(arr.dtype)

int32


# Converting Data Type on Existing Arrays- astype

In [45]:
arr = np.array([1.1, 2.1, 3.1])
newarr = arr.astype('i')
print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [46]:
arr = np.array([1.1, 2.1, 3.1])
newarr = arr.astype(int)

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [47]:
arr = np.array([1, 0, 3])
newarr = arr.astype(bool)
print(newarr)
print(newarr.dtype)

[ True False  True]
bool


# 7.copy

In [48]:
arr=np.array([1,2,3,4])
x=arr.copy()
arr[0]=25# changing the first element
print(arr)
print(x)

[25  2  3  4]
[1 2 3 4]


In [49]:
# The copy SHOULD NOT be affected by the changes made to the original array

# 8. view

In [50]:
arr=np.array([1,2,3,4])
x=arr.view()
arr[0]=25# changing the first element
print(arr)
print(x)

[25  2  3  4]
[25  2  3  4]


In [51]:
#The view SHOULD be affected by the changes made to the original array.

In [52]:
arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[1 2 3 4 5]


# 9.shape of the array

In [53]:
#The shape of an array is the number of elements in each dimension.



# Get the Shape of an Array-shape

In [54]:
arr = np.array([1, 2, 3, 4, 5])
print(arr.shape)# total 5 rows five elements

(5,)


In [55]:
arr2=np.array([[1,2,3],[4,5,6],[3,4,5],[9,1,6]])
print(arr2.shape)# 4 rows 3 columns, 4 elements consist 3 elements in each 

(4, 3)


In [56]:
arr3=np.array([[[1,2,3],[4,5,6]], [[6,2,3],[4,5,6]]])
print(arr3.shape)# 2 3d elements,2 2d elements , 3 1d elements

(2, 2, 3)


In [57]:
b=np.array([1,2,3],ndmin=5)
print(b.shape)

(1, 1, 1, 1, 3)


# 10.Reshape 

# From 1-D to 2-D- reshape

In [58]:
arr = np.array([1, 2, 3, 4, 5,6])
nwarr=arr.reshape(3,2)# 2 element ulla 3 ennam ,reshape(no.of elements in 2d,no.of elements in 1d)
print(nwarr)

[[1 2]
 [3 4]
 [5 6]]


# From 1-D to 3-D- reshape

In [59]:
arr = np.array([1, 2, 3, 4, 5,6,7,8,9,10,11,12])
nwarr=arr.reshape(2,3,2)# 3d 2 elements ,2d 3 elements ,1d 2 elements
print(nwarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [60]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(arr.reshape(2, 4).base)

[1 2 3 4 5 6 7 8]


In [61]:
# The example above returns the original array, so it is a view.not copy



# multidimensional array into a 1D array.-reshape(-1)

In [62]:
arr3=np.array([[[1,2,3],[4,5,6]], [[6,2,3],[4,5,6]]])
print(arr3.reshape(-1))

[1 2 3 4 5 6 6 2 3 4 5 6]


# 11.Iterating Arrays

In [63]:
# Iterating means going through elements one by one.,for loop

# 1d array

In [64]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
for i in arr:
    print(i)

1
2
3
4
5
6
7
8


# 2d array

In [65]:
arr2=np.array([[1,2,3],[5,6,7]])
for i in arr2:
    print(i)

[1 2 3]
[5 6 7]


#Iterate on each scalar element of the 2-D array:

In [66]:
arr2=np.array([[1,2,3],[5,6,7]])
for x in arr2:
    for y in x:
        print(y)
    

1
2
3
5
6
7


# 3d array

In [67]:
arr3 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
for i in arr3:
    print(i)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [68]:
#Iterate down to the scalars:

In [69]:
arr3 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
for x in arr3:
    for y in x:
        for z in y:
            print(z)

1
2
3
4
5
6
7
8
9
10
11
12


In [70]:
arr3 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
for x in arr3:
    for y in x:
            print(y)

[1 2 3]
[4 5 6]
[7 8 9]
[10 11 12]


# Iterating Arrays Using - nditer()

In [71]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
for i in np.nditer(arr):
    print(i)

1
2
3
4
5
6
7
8


In [72]:
arr3 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
for i in np.nditer(arr3):
    print(i)


1
2
3
4
5
6
7
8
9
10
11
12


# Iterating With Different Step Size

In [73]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
for x in np.nditer(arr[:, ::2]):
  print(x)

1
3
5
7


# Iterating Array With Different Data Types- op_dtypes

In [74]:
arr = np.array([1, 2, 3])
for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
  print(x)

b'1'
b'2'
b'3'


# Enumerated Iteration Using ndenumerate()

In [75]:
arr = np.array([1, 2, 3])
for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0,) 1
(1,) 2
(2,) 3


In [76]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


# 12 . Joining Arrays-concatenate()

In [77]:
#Joining means putting contents of two or more arrays in a single array.

# 1d array

In [78]:
arr1=np.array([1,2,3,4])
arr2=np.array([1,2,3,0])
arr=np.concatenate((arr1,arr2))
print(arr)

[1 2 3 4 1 2 3 0]


# 2d array

In [79]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr = np.concatenate((arr1, arr2), axis=1)# axis 1 is making concatenate
print(arr)

[[1 2 5 6]
 [3 4 7 8]]


# Joining Arrays Using Stack Functions

In [80]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr = np.stack((arr1, arr2), axis=1)# axis 1 is making concatenate
print(arr)

[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]


# Stacking Along Rows-hstack() to stack along rows

In [81]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.hstack((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


# Stacking Along Columns-vstack()  to stack along columns.

In [82]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.vstack((arr1, arr2))
print(arr)

[[1 2 3]
 [4 5 6]]


# Stacking Along Height (depth)-dstack() to stack along height

In [83]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.dstack((arr1, arr2))
print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


# 13.Splitting NumPy Arrays-array_split()

In [84]:
#Splitting is reverse operation of Joining.-

In [85]:
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 3)# 3 is the number of arrays
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [86]:
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 2)# 2 is the number of arrays
print(newarr)

[array([1, 2, 3]), array([4, 5, 6])]


In [87]:
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 4)
print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [88]:
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 3)
print(newarr[0])
print(newarr[1])
print(newarr[2])

[1 2]
[3 4]
[5 6]


# 2d array

In [89]:
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])
newarr = np.array_split(arr, 3)# 3 two dim arrayas will come
print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [90]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
newarr = np.array_split(arr, 3)
print(newarr)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


In [91]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3,axis=1)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


# 14. searching arrays- where()

In [92]:
arr=np.array([1,2,3,4,5,6])
x=np.where(arr==4)# 4 varunna index position kaanich tharum
print(x)#Find the indexes where the value is 4:

(array([3], dtype=int64),)


In [93]:
arr=np.array([1,2,3,4,5,6])
x=np.where(arr%2==0)#Find the indexes where the values are even:
print(x)

(array([1, 3, 5], dtype=int64),)


In [94]:
arr=np.array([1,2,3,4,5,6])
x=np.where(arr%2==1)#Find the indexes where the values are odd:
print(x)

(array([0, 2, 4], dtype=int64),)


# searchsorted()

In [95]:
arr = np.array([6, 7, 8, 9])
x = np.searchsorted(arr, 7)# Find the indexes where the value 7 should be inserted:
print(x)

1


In [96]:
arr = np.array([6, 7, 8, 9])
x = np.searchsorted(arr, 7, side='right')#Find the indexes where the value 7 should be inserted, starting from the right:
print(x)

2


In [97]:
arr = np.array([1, 3, 5, 7])
x = np.searchsorted(arr, [2, 4, 6])#Find the indexes where the values 2, 4, and 6 should be inserted:
print(x)

[1 2 3]


# 15.Sorting Arrays-sort()

In [98]:
#Sorting means putting elements in an ordered sequence.

# 1d array

In [99]:
arr = np.array([3, 2, 0, 1])
print(np.sort(arr))# ascending order

[0 1 2 3]


In [100]:
arr = np.array(['banana', 'cherry', 'apple'])
print(np.sort(arr))# alphabetical order

['apple' 'banana' 'cherry']


In [101]:
arr = np.array([True, False, True])
print(np.sort(arr))

[False  True  True]


# 2d array

In [102]:
arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))#If you use the sort() method on a 2-D array, both arrays will be sorted

[[2 3 4]
 [0 1 5]]


# 16. Filtering Arrays

In [103]:
# Getting some elements out of an existing array and creating a new array out of them is called filtering.
#A boolean index list is a list of booleans corresponding to indexes in the array.

#If the value at an index is True that element is contained in the filtered array,
#if the value at that index is False that element is excluded from the filtered array.

In [104]:
arr = np.array([41, 42, 43, 44])
x = [True, False, True, False]
newarr = arr[x]
print(newarr)

[41 43]
